package SubTelas.Estoque;

import Commun.TextPrompt;
import Dao.EstoqueDao;
import Pacotes.Produto;
import java.awt.Insets;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import telas.Estoque;

public class EditarProduto extends javax.swing.JFrame {

    TextPrompt nomes;
    EstoqueDao produtoDao = new EstoqueDao();
    Estoque atualizar;

    public EditarProduto() {
        initComponents();
    }

    public EditarProduto(Estoque atualizar, int codigo) {
        initComponents();
        nomes = new TextPrompt("Nome", txtNome);
        nomes = new TextPrompt("Código", txtCodigo);
        nomes = new TextPrompt("Data de Vencimento", txtVencimento);
        nomes = new TextPrompt("Quantidade", txtQuantidade);
        nomes = new TextPrompt("Quantidade Ideal", txtMinimo);
        nomes = new TextPrompt("Valor", txtValor);
        this.atualizar = atualizar;
        mostrarProduto(codigo);
    }
    
    public EditarProduto(int codigo) {
        initComponents();
        nomes = new TextPrompt("Nome", txtNome);
        nomes = new TextPrompt("Código", txtCodigo);
        nomes = new TextPrompt("Data de Vencimento", txtVencimento);
        nomes = new TextPrompt("Quantidade", txtQuantidade);
        nomes = new TextPrompt("Quantidade Ideal", txtMinimo);
        nomes = new TextPrompt("Valor", txtValor);
        lblTitulo.setText("Visualizar Produto");
        lblRs.setEnabled(false);
        btnCadrastar.setVisible(false);
        txtCodigo.setEnabled(false);
        txtNome.setEnabled(false);
        txtValor.setEnabled(false);
        txtQuantidade.setEnabled(false);
        txtMinimo.setEnabled(false);
        cbPerecivel.setEnabled(false);
        txtVencimento.setEnabled(false);
        mostrarProduto(codigo);     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbPerecivel = new javax.swing.JCheckBox();
        btnCadrastar = new javax.swing.JButton();
        txtVencimento = new javax.swing.JFormattedTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtMinimo = new javax.swing.JTextField();
        lblRs = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Produto");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCodigo.setEnabled(false);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 190, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Editar Produtos");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 590, 40));

        txtNome.setBackground(new java.awt.Color(236, 236, 236));
        txtNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 420, -1));

        cbPerecivel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbPerecivel.setText("Perecível?");
        cbPerecivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbPerecivelMouseClicked(evt);
            }
        });
        cbPerecivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerecivelActionPerformed(evt);
            }
        });
        getContentPane().add(cbPerecivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        btnCadrastar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Icons/iconeSalvar.png"))); // NOI18N
        btnCadrastar.setText("Salvar");
        btnCadrastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadrastarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadrastar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 120, 40));

        txtVencimento.setBackground(new java.awt.Color(236, 236, 236));
        try {
            txtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVencimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVencimentoFocusLost(evt);
            }
        });
        getContentPane().add(txtVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, 25));

        txtQuantidade.setBackground(new java.awt.Color(236, 236, 236));
        txtQuantidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, -1));

        txtMinimo.setBackground(new java.awt.Color(236, 236, 236));
        txtMinimo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(txtMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 190, -1));

        lblRs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRs.setText("R$:");
        lblRs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblRs, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 30, 27));

        txtValor.setBackground(new java.awt.Color(236, 236, 236));
        txtValor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtValor.setMargin(new java.awt.Insets(2, 25, 2, 2));
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tela_branca.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 380));

        setSize(new java.awt.Dimension(614, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadrastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadrastarActionPerformed
        Produto prod = new Produto();
        
        if (!txtNome.getText().equalsIgnoreCase("")) {
            prod.setNomeProduto(txtNome.getText());
        } else {
            JOptionPane.showMessageDialog(null, "O campo Nome não pode está vazio");
            return;
        }
        
        try {
            if (!txtCodigo.getText().equalsIgnoreCase("")) {
                prod.setIdProduto(Integer.parseInt(txtCodigo.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "O campo Codigo não pode está vazio");
                return;
            }
            if (!txtQuantidade.getText().equalsIgnoreCase("")) {
                prod.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "O campo Quantidade não pode está vazio");
                return;
            }
            if (!txtMinimo.getText().equalsIgnoreCase("")) {
                prod.setQuantidadeIdeal(Integer.parseInt(txtMinimo.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "O campo Quantidade ideal não pode está vazio");
                return;
            }
            if (!txtValor.getText().equalsIgnoreCase("")){
                prod.setValorProduto(Double.parseDouble(txtValor.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "O campo valor não pode está vazio");
                return;
            }         
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "A campos numericom com letra");
        }     
        if (!txtVencimento.getText().equalsIgnoreCase("") && !txtVencimento.getText().equalsIgnoreCase("  /  /    ")){
            prod.setDataStr(txtVencimento.getText().substring(6) + "-" + txtVencimento.getText().substring(3, 5) + "-" + txtVencimento.getText().substring(0, 2));
        } else{
            prod.setDataStr("1800-01-01");             
        }
      
       Salvar(prod);
    }//GEN-LAST:event_btnCadrastarActionPerformed

    private void cbPerecivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPerecivelMouseClicked
        if (cbPerecivel.isSelected()) {
            txtVencimento.setVisible(true);
        } else {
            txtVencimento.setVisible(false);
        }
    }//GEN-LAST:event_cbPerecivelMouseClicked

    private void txtVencimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFocusGained
        try{
            MaskFormatter vencimento = new MaskFormatter("##/##/####");
            txtVencimento.setFormatterFactory(new DefaultFormatterFactory(vencimento));
        }catch(ParseException ex){
            System.out.println("Erro na mascara do vencimento");
        }
    }//GEN-LAST:event_txtVencimentoFocusGained

    private void txtVencimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVencimentoFocusLost
        try{
            MaskFormatter vazio = new MaskFormatter("");
            if(txtVencimento.getText().equalsIgnoreCase("  /  /    ") | txtVencimento.getText().replace(" ", "").replace("/", "").length() < 8){
                txtVencimento.setFormatterFactory(new DefaultFormatterFactory(vazio));
            }
        }catch(ParseException ex){
            System.out.println("Erro na mascara do vencimento");
        }
    }//GEN-LAST:event_txtVencimentoFocusLost

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        Insets espaco = new Insets(2, 25, 2, 2);
        if(txtValor.getText().equalsIgnoreCase("")){
            txtValor.setMargin(espaco);
            lblRs.setVisible(true);           
        }
    }//GEN-LAST:event_txtValorFocusGained

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
          Insets espaco = new Insets(2, 2, 2, 2);
        if(txtValor.getText().equalsIgnoreCase("")){
            txtValor.setMargin(espaco);
            lblRs.setVisible(false);
        }
    }//GEN-LAST:event_txtValorFocusLost

    private void cbPerecivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerecivelActionPerformed
        if(!cbPerecivel.isSelected()){
            txtVencimento.setText("");
        }
    }//GEN-LAST:event_cbPerecivelActionPerformed

    private void mostrarProduto(int codigo){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Produto produto;
        
        if(produtoDao.conectar()){
            produto = produtoDao.buscar(codigo);
            if(produto != null){
                try {
                    txtCodigo.setText(String.valueOf(codigo));
                    txtNome.setText(produto.getNomeProduto());
                    txtQuantidade.setText(String.valueOf(produto.getQuantidade()));
                    txtMinimo.setText(String.valueOf(produto.getQuantidadeIdeal()));
                    txtValor.setText(String.valueOf(produto.getValorProduto()));
                    if(produto.getData().after(formato.parse("02/01/1800"))){
                        txtVencimento.setValue(formato.format(produto.getData()));
                        cbPerecivel.setSelected(true);
                    }else{
                        cbPerecivel.setSelected(false);
                        txtVencimento.setVisible(false);
                    }
                } catch (ParseException ex) {
                    System.err.println(ex.getMessage());
                    dispose();
                }

            }else{
                JOptionPane.showMessageDialog(null, "Erro ao buscar os dados do produto", "Erro", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
            produtoDao.desconectar();
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }
    
    
    private void Salvar(Produto produto) {
        boolean resultado;
        
        if (produtoDao.conectar()) {
            resultado = produtoDao.alterar(produto);
            if (resultado) {
                JOptionPane.showMessageDialog(null, "Produto salvo com sucesso");
                this.atualizar.atualizar();
                dispose();
            }else {
                JOptionPane.showMessageDialog(null, "Não foi possivel salvar o produto");
            }
            produtoDao.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    public static void editar(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btnCadrastar;
    private javax.swing.JCheckBox cbPerecivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRs;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMinimo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    private javax.swing.JFormattedTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
